version: "3"
services:
  app:
    build: .
    volumes:
      - .:/go/src/github.com/hiroara/bunshin-no-jutsu
      - go-pkg-mod:/go/pkg/mod
      - home-cache:/root/.cache
    environment:
      - GO111MODULE=on
volumes:
  go-pkg-mod:
  home-cache:
